### ISSUE TITLE
Possible bug with using same class in multiple parents

### ISSUE THREAD

**Issue by joshbthomp** [mbknor/mbknor-jackson-jsonSchema#24]
Hi, 
I am running into an issue where I am using the same class in two different objects which both subclass a parent abstract class (see error below)  I have created a full working example in Java that can be found [here](https://github.com/joshbthomp/JsonSchemaGeneratorBugTest).  The code can be ran from the main method in SchemaGenerator.java.  It may be something simple like a missing annotation or something but I am not sure.  Please let me know if you need additional information.

```
Exception in thread "main" java.lang.Exception: Wrong class - working on class model.entities.Person - got class model.properties.Address
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$DefinitionsHandler.getOrCreateDefinition(JsonSchemaGenerator.scala:163)
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$MyJsonFormatVisitorWrapper.expectObjectFormat(JsonSchemaGenerator.scala:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:809)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:580)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:3650)
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$anonfun$7$$anon$7.myPropertyHandler(JsonSchemaGenerator.scala:648)
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$anonfun$7$$anon$7.optionalProperty(JsonSchemaGenerator.scala:703)
```

**Comment by mbknor** [comment]
Thanks for supplying https://github.com/joshbthomp/JsonSchemaGeneratorBugTest - I've added it as testcase  - failing for the time being..

I'll look into it.

**Comment by joshbthomp** [comment]
Sounds good!  I'll be looking forward to your next release :-)

**Comment by mbknor** [comment]
@joshbthomp It should work now. Please try it out by building it yourself

**Comment by roee88** [comment]
@mbknor  
Did you miss a commit? code refers to pushWorkInProgress which does not exist (but pushq does).
Also, should the stack only be used there? e.g., what if the property is of type Optional?
Thanks.

**Comment by mbknor** [comment]
Looks like there was a typo in the last commit. This is fixed now.

I just now also noticed tha push/pop should laso be used one more place. Not sure if this is what you refere to with 'type Optional'
