### ISSUE TITLE
The Shema Generator ignores JsonSubTypes-Infos added via JacksonMixInAnnotations

### ISSUE THREAD

**Issue by MaximilianFranke** [mbknor/mbknor-jackson-jsonSchema#6]
JsonSubTypes-Infos added via JacksonMixInAnnotations ( see http://wiki.fasterxml.com/JacksonMixInAnnotations ) are ignored.

Here is my sample Code, written in Java:
```
// sample_zoo.json:
//{
//	"animals":
//     [
//       {"type":"dog","name":"Spike","breed":"mutt",
//           "leashColor":"red"},
//       {"type":"cat","name":"Fluffy",
//           "favoriteToy":"spider ring"}
//     ]
//}

package jacksontest;

import java.util.List;

import org.slf4j.Logger;

import scala.Option;
import scala.Some;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.module.SimpleModule;
import com.kjetland.jackson.jsonSchema.JsonSchemaConfig;
import com.kjetland.jackson.jsonSchema.JsonSchemaGenerator;

public class Foo {
	static Logger logger = org.slf4j.LoggerFactory.getLogger(Foo.class);

	static class Zoo {
		public List<Animal> animals;
	}

	static abstract class Animal {
		public String name;
	}

	static class Dog extends Animal {
		public String breed;
		public String leashColor;
	}

	static class Cat extends Animal {
		public String favoriteToy;
	}

	static class MyModule extends SimpleModule {
		@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
		@JsonSubTypes({ @Type(value = Dog.class, name = "dog"), @Type(value = Cat.class, name = "cat") })
		abstract class MixIn {

		}

		@Override
		public void setupModule(SetupContext context) {
			context.setMixInAnnotations(Animal.class, MixIn.class);
		}
	}

	public static void main(String[] args) throws Exception {
		ObjectMapper mapper = new ObjectMapper();
		mapper.registerModule(new MyModule());

		// jackson read and write test
		Zoo zoo = mapper.readValue(Foo.class.getResourceAsStream("./sample_zoo.json"), Zoo.class);
		logger.info(mapper.writerWithDefaultPrettyPrinter().writeValueAsString(zoo));

		// Html5 Schema generator test
		try {
			JsonSchemaGenerator html5 = new JsonSchemaGenerator(mapper, JsonSchemaConfig.html5EnabledSchema());
			Option<String> title = new Some<String>("MyZooTitle");
			Option<String> description = new Some<String>("MyZooDescription");
			JsonNode schema = html5.generateJsonSchema(Zoo.class, title, description);
			logger.info(mapper.writerWithDefaultPrettyPrinter().writeValueAsString(schema));
		} catch (Exception e) {
			logger.error("Unexpected exception", e);
		}

	}
}
```

Here is the output with Exception:
```
2016-10-04T10:36:01.730 INFO  [jacksontest.Foo] - {
  "animals" : [ {
    "type" : "dog",
    "name" : "Spike",
    "breed" : "mutt",
    "leashColor" : "red"
  }, {
    "type" : "cat",
    "name" : "Fluffy",
    "favoriteToy" : "spider ring"
  } ]
}
2016-10-04T10:36:01.845 ERROR [jacksontest.Foo] - Unexpected exception
java.lang.Exception: Did not find info about the class class jacksontest.Foo$Animal in @JsonSubTypes
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$anonfun$com$kjetland$jackson$jsonSchema$JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$extractPolymorphismInfo$1$$anonfun$3$$anonfun$apply$12.apply(JsonSchemaGenerator.scala:435)
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$anonfun$com$kjetland$jackson$jsonSchema$JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$extractPolymorphismInfo$1$$anonfun$3$$anonfun$apply$12.apply(JsonSchemaGenerator.scala:435)
	at scala.Option.getOrElse(Option.scala:121)
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$anonfun$com$kjetland$jackson$jsonSchema$JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$extractPolymorphismInfo$1$$anonfun$3.apply(JsonSchemaGenerator.scala:435)
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$anonfun$com$kjetland$jackson$jsonSchema$JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$extractPolymorphismInfo$1$$anonfun$3.apply(JsonSchemaGenerator.scala:431)
	at scala.Option.map(Option.scala:146)
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$anonfun$com$kjetland$jackson$jsonSchema$JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$extractPolymorphismInfo$1.apply(JsonSchemaGenerator.scala:430)
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$anonfun$com$kjetland$jackson$jsonSchema$JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$extractPolymorphismInfo$1.apply(JsonSchemaGenerator.scala:421)
	at scala.Option.map(Option.scala:146)
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$MyJsonFormatVisitorWrapper.com$kjetland$jackson$jsonSchema$JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$extractPolymorphismInfo(JsonSchemaGenerator.scala:420)
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$anonfun$8.apply(JsonSchemaGenerator.scala:510)
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$anonfun$8.apply(JsonSchemaGenerator.scala:483)
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$DefinitionsHandler.getOrCreateDefinition(JsonSchemaGenerator.scala:184)
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$MyJsonFormatVisitorWrapper.expectObjectFormat(JsonSchemaGenerator.scala:704)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:809)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:580)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:3641)
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$anon$2.itemsFormat(JsonSchemaGenerator.scala:286)
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$anonfun$8$$anon$7.myPropertyHandler(JsonSchemaGenerator.scala:611)
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$MyJsonFormatVisitorWrapper$$anonfun$8$$anon$7.optionalProperty(JsonSchemaGenerator.scala:680)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.depositSchemaProperty(BeanPropertyWriter.java:805)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:833)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:580)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:3641)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:3620)
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator.generateJsonSchema(JsonSchemaGenerator.scala:807)
	at jacksontest.Foo.main(Foo.java:76)
```

**Comment by mbknor** [comment]
Thanks. I have not used this MixIn-approache before, but I'll see what I can do.

**Comment by MaximilianFranke** [comment]
The same problem is with programmatically registered types:
`mapper.registerSubtypes(new NamedType(Dog.class, "dog"), new NamedType(Cat.class, "cat"));`

**Comment by mbknor** [comment]
I think I've now fixed both using Mixin and registerSubtypes.. Please confirm.
If you confirm it within the hour, I'll release it to Maven Central tonight (Norwegian Time)

**Comment by MaximilianFranke** [comment]
Thank you! It works fine for me!

**Comment by mbknor** [comment]
1.0.8 has now been released
