### ISSUE TITLE
Dependency to too 'old' fast-classpath-scanner version 2.0.20 fails schema generation

### ISSUE THREAD

**Issue by paskos** [mbknor/mbknor-jackson-jsonSchema#64]
We're using mbknor-jackson-jsonschema_2.12 version 1.0.28

when asm 6.0 is in the classpath fast-classpath-scanner version 2.0.20 fails the schema generation with 

```java
Caused by: java.lang.RuntimeException: Unknown constant pool tag [I@3d565ef8 in classfile module-info.class (element size unknown, cannot continue reading class. Please report this on the FastClasspathScanner GitHub page.
	at io.github.lukehutch.fastclasspathscanner.scanner.ClassfileBinaryParser.readClassInfoFromClassfileHeader(ClassfileBinaryParser.java:562)
	at io.github.lukehutch.fastclasspathscanner.scanner.ClasspathElementZip.openInputStreamAndParseClassfile(ClasspathElementZip.java:306)
	at io.github.lukehutch.fastclasspathscanner.scanner.ClasspathElement.parseClassfiles(ClasspathElement.java:321)
	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner$3.processWorkUnit(Scanner.java:373)
	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner$3.processWorkUnit(Scanner.java:367)
	at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue.runWorkLoop(WorkQueue.java:133)
	... 6 common frames omitted
```

It's a fixed bug in fast-classpath-scanner [issue #141](https://github.com/lukehutch/fast-classpath-scanner/issues/141)

**Comment by mbknor** [comment]
version 1.0.29 released and on its way to maven central
