### ISSUE TITLE
Support multiple levels of inheritence through JsonTypeIdResolver

### ISSUE THREAD

**Issue by AlexBroadbent** [mbknor/mbknor-jackson-jsonSchema#85]
A JSON schema cannot be produced for a class which has multiple levels of inheritance, when using the `@JsonTypeIdResolver` annotation (with a `CUSTOM` use `@JsonTypeInfo` annotation). 

This is supported through the `@JsonSubTypes` annotation).

---

### Code to reproduce

Having a base class:
```java
@JsonTypeInfo(use = Id.CUSTOM, include = As.EXISTING_PROPERTY, property = "name")
@JsonTypeIdResolver(AnimalTypeIdResolver.class)
public abstract class Animal {
  @JsonProperty
  private String name;
}
```

With extension classes:
```java
public static final class Cat extends Animal {
  public Cat() { super("cat"); }
}
```

```java
public static final class Dog extends Animal {
  public Dog() { super("dog"); }
}
```

And a TypeIdResolver to map our :
```java
public static class AnimalTypeIdResolver extends TypeIdResolverBase {
  private JavaType superType;

  public void init(JavaType baseType) { superType = baseType; }

  public Id getMechanism() { return Id.CUSTOM; }

  public String idFromValue(Object object) { return idFromValueAndType(object, object.getClass()); }

  public String idFromValueAndType(Object object, Class<?> subType) {
    String typeId = null;
    switch (subType.getSimpleName()) {
      case "Cat":
        typeId = "cat";
        break;
      case "Dog":
        typeId = "dog";
        break;
    }
    return typeId;
  }

  public JavaType typeFromId(DatabindContext context, String id) {
    Class<?> subType = null;
    switch (id) {
      case "cat":
        subType = Cat.class;
        break;
      case "dog":
        subType = Dog.class;
        break;
    }
    return context.constructSpecializedType(superType, subType);
  }

}
```

We get the expected schema when generating one from the `Animal` subclass:
```json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Animal",
	"oneOf": [{
		"$ref": "#/definitions/Cat"
  }, {
		"$ref": "#/definitions/Dog"
  }],
	"definitions": {
		"Cat": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"name": {
					"type": "string",
					"enum": ["cat"],
					"default": "cat"
				}
			},
			"title": "cat",
			"required": ["name"]
		},
		"Dog": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"name": {
					"type": "string",
					"enum": ["dog"],
					"default": "dog"
				}
			},
			"title": "dog",
			"required": ["name"]
		}
	}
}
```

---

### Refactoring Hierarchy

When we adjust `Dog` to be an `abstract class`, with extensions of `Poodle` and `Dachshund`; as such:
```java
public static abstract class Dog extends Animal {
  public Dog(String name) {
    super(name);
  }
}
```

```java
public static final class Poodle extends Dog {
  public Poodle() {
    super("poodle");
  }
}
```

```java
public static final class Dachshund extends Dog {
  public Dachshund() {
    super("dachshund");
  }
}
```

Then we refactor the `AnimalTypeIdResolver` methods to:
```java
public String idFromValueAndType(Object object, Class<?> subType) {
  String typeId = null;
  switch (subType.getSimpleName()) {
    case "Cat":
      typeId = "cat";
      break;
    case "Poodle":
      typeId = "poodle";
      break;
    case "Dachshund":
      typeId = "dachshund";
      break;
  }
  return typeId;
}

public JavaType typeFromId(DatabindContext context, String id) {
  Class<?> subType = null;
  switch (id) {
    case "cat":
      subType = Cat.class;
      break;
    case "poodle":
      subType = Poodle.class;
      break;
    case "dachshund":
      subType = Dachshund.class;
      break;
  }
  return context.constructSpecializedType(superType, subType);
}
```

---

Now when generating a JSON schema of the `Animal` class, we get the error:

```
Wrong class - working on class com.kjetland.jackson.jsonSchema.testData.Animal$Dog - got class com.kjetland.jackson.jsonSchema.testData.Animal$Dachsund
java.lang.Exception: Wrong class - working on class com.kjetland.jackson.jsonSchema.testData.Animal$Dog - got class com.kjetland.jackson.jsonSchema.testData.Animal$Dachsund
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$DefinitionsHandler.getOrCreateDefinition(JsonSchemaGenerator.scala:344)
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$MyJsonFormatVisitorWrapper.$anonfun$expectObjectFormat$1(JsonSchemaGenerator.scala:908)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at com.kjetland.jackson.jsonSchema.JsonSchemaGenerator$MyJsonFormatVisitorWrapper.expectObjectFormat(JsonSchemaGenerator.scala:904)
...
```

---

As mentioned before, using JsonSubTypes produces the expected JSON schema correctly; this can be done by changing the annotations on `Animal` to:
```java
@JsonTypeInfo(use = Id.NAME, include = As.EXISTING_PROPERTY, property = "name")
@JsonSubTypes({
    @Type(name = "cat", value = Cat.class),
    @Type(name = "poodle", value = Poodle.class),
    @Type(name = "dachshund", value = Dachshund.class)
})
public abstract class Animal {
...
}
```

**Comment by mbknor** [comment]
If you are still interested in this problem, please provide PR where you add test-case (in the same way that other tests in this project are implemented) which fails.... This will make it more easy to investigate.

If not, I'll close this issue later
